const STORAGE='rayburnHerdV2';
const INITIAL_DATA=[
  {
    "id": "a1",
    "category": "Bull",
    "tag": "1",
    "oldTag": "#250 Red",
    "name": "Fernando",
    "currentCalf": "NA",
    "dob": "2022-01-01",
    "notes": "Purchased April 2023 for $3000, breeding bull for herd",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a2",
    "category": "Cow",
    "tag": "2",
    "oldTag": "No Tag",
    "name": "Blue",
    "currentCalf": "14 Pink",
    "dob": "2023-01-01",
    "notes": "Bucket Calf we raised. Had her first calf in December 2024 #6 . 2nd on 17 Dec 25 (#14 Pink)",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a3",
    "category": "Cow",
    "tag": "3",
    "oldTag": "#5 Blue",
    "name": "",
    "currentCalf": "16 Pink",
    "dob": "2022-01-01",
    "notes": "Had three calves; Heifer #2 White (sold), Bull #7(sold) and #16 pink born on 25 December.",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a4",
    "category": "Cow",
    "tag": "4",
    "oldTag": "#70 White",
    "name": "",
    "currentCalf": "Lost",
    "dob": "2022-01-01",
    "notes": "First calf lost in Jan 2024; Second calf #8 White born Jan 12, 2025 sold. Third calf born 20 Jan 2026(#17 Blue-Died)",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a5",
    "category": "Cow",
    "tag": "5",
    "oldTag": "#69 Red",
    "name": "",
    "currentCalf": "15 Pink",
    "dob": "2022-01-01",
    "notes": "Had three calves; Heifer #3 White (sold), Heifer #9  (sold) and Pink 15 born Dec 22 2025 (11 month after)",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a6",
    "category": "Cow",
    "tag": "6",
    "oldTag": "#14 Yellow/No Tag",
    "name": "",
    "currentCalf": "34 Pink",
    "dob": "2022-01-01",
    "notes": "Had two calves; first sold, second born Feb 11, 2025 (Bull #10 White) She should have had a calf in Feb 2026 but didn't ",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a7",
    "category": "Cow",
    "tag": "7",
    "oldTag": "",
    "name": "",
    "currentCalf": "25 Blue",
    "dob": "2024-03-01",
    "notes": "1st Calf Steer #25 Blue born mid March 2026.",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a8",
    "category": "Cow",
    "tag": "8",
    "oldTag": "",
    "name": "",
    "currentCalf": "27 Blue",
    "dob": "2024-03-01",
    "notes": "1nd Calf Steer #27 Blue born late March 2026.",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a9",
    "category": "Cow",
    "tag": "9",
    "oldTag": "",
    "name": "",
    "currentCalf": "31 Pink",
    "dob": "2024-03-01",
    "notes": "Pregnant and due Apr 2026",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a10",
    "category": "Cow",
    "tag": "10",
    "oldTag": "",
    "name": "",
    "currentCalf": "24 Pink",
    "dob": "2024-03-01",
    "notes": "1st Calf Born 01 April 26. Black White Face",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a11",
    "category": "Cow",
    "tag": "11",
    "oldTag": "",
    "name": "",
    "currentCalf": "20 Pink",
    "dob": "2024-03-01",
    "notes": "1st calf early March 2026 (#20 Pink) Good mama",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a12",
    "category": "Cow",
    "tag": "12",
    "oldTag": "",
    "name": "",
    "currentCalf": "23 Pink (Mo)",
    "dob": "2024-03-01",
    "notes": "1st Calf early March 2026. Bad Mama--Didn't take to the calf. (Mo) ",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a13",
    "category": "Cow",
    "tag": "13",
    "oldTag": "",
    "name": "",
    "currentCalf": "21 Pink",
    "dob": "2024-03-01",
    "notes": "Dropped 1st Calf early March 2026. Good Mama-#21 Pink",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a14",
    "category": "Cow",
    "tag": "14",
    "oldTag": "",
    "name": "",
    "currentCalf": "26 Blue",
    "dob": "2024-03-01",
    "notes": "1st Calf Steer #27 Blue born late March 2026.",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a15",
    "category": "Cow",
    "tag": "15",
    "oldTag": "",
    "name": "",
    "currentCalf": "22 Blue",
    "dob": "2024-03-01",
    "notes": "1st Calf early March 2026 (#22 Pink) Good Mama. ",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a16",
    "category": "Cow",
    "tag": "16",
    "oldTag": "",
    "name": "",
    "currentCalf": "28 Pink",
    "dob": "2024-03-01",
    "notes": "1st Calf heifer born early April 28 Pink",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a17",
    "category": "Cow",
    "tag": "17",
    "oldTag": "",
    "name": "",
    "currentCalf": "18 Blue",
    "dob": "2024-03-01",
    "notes": "1st Calf steer born early March #18 Blue",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a18",
    "category": "Cow",
    "tag": "18",
    "oldTag": "",
    "name": "",
    "currentCalf": "19 Pink",
    "dob": "2024-03-01",
    "notes": "Dropped her first half early March 2026 (#19 Pink) good mama.",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a19",
    "category": "Cow",
    "tag": "19",
    "oldTag": "#50 Red",
    "name": "Clementine",
    "currentCalf": "30 Blue",
    "dob": "2024-02-01",
    "notes": "Purchased March 2024 for $200; First Calf born April 07. Bad Mama didn't want calf. ",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a20",
    "category": "Cow",
    "tag": "20",
    "oldTag": "#22 White",
    "name": "",
    "currentCalf": "29 Blue",
    "dob": "2023-01-01",
    "notes": "Had first calf on May 14, 2025: Bull #11 Blue 29 01 April",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a21",
    "category": "Cow",
    "tag": "21",
    "oldTag": "Delilah",
    "name": "Delilah",
    "currentCalf": "",
    "dob": "2021-01-01",
    "notes": "Had three calves: Lil' Money (#4 White) on June 19, 2024; Heifer #12 Blue on May 26, 2025; One earlier one April 2026",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a22",
    "category": "Cow",
    "tag": "22",
    "oldTag": "#78 Blue",
    "name": "",
    "currentCalf": "32 Pink",
    "dob": "2023-01-01",
    "notes": "Had first calf on May 31, 2025: Heifer #13 Blue",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a23",
    "category": "Cow",
    "tag": "23",
    "oldTag": "#6 Yellow",
    "name": "",
    "currentCalf": "",
    "dob": "2023-01-01",
    "notes": "Purchased July 2024 from Rayburn Enterprises (No Calf and large Abcess)1st Calf 15 June 2026 (off cycle)",
    "status": "active",
    "motherTag": "",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a24",
    "category": "Calf - Heifer",
    "tag": "14 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2025-12-01",
    "notes": "Born to Blue. (#2) Her second Calf.  ",
    "status": "active",
    "motherTag": "2",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a25",
    "category": "Calf - Heifer",
    "tag": "15 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2025-12-01",
    "notes": "Born to (#5) Her third calf. ",
    "status": "active",
    "motherTag": "5",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a26",
    "category": "Calf - Heifer",
    "tag": "16 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-01-01",
    "notes": "Born Blue. (#3) Her third Calf.  ",
    "status": "active",
    "motherTag": "3",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a27",
    "category": "Calf - Steer",
    "tag": "18 Blue",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-03-01",
    "notes": "Born to # 17 Good mama",
    "status": "active",
    "motherTag": "17",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a28",
    "category": "Calf - Heifer",
    "tag": "19 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-03-01",
    "notes": "Born to #18 good mama",
    "status": "active",
    "motherTag": "18",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a29",
    "category": "Calf - Heifer",
    "tag": "20 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-03-01",
    "notes": "Born to #11 good mama",
    "status": "active",
    "motherTag": "11",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a30",
    "category": "Calf - Heifer",
    "tag": "21 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-03-01",
    "notes": "Born to #13 good mama",
    "status": "active",
    "motherTag": "13",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a31",
    "category": "Calf - Heifer",
    "tag": "22 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-03-01",
    "notes": "Born to #15 good mama",
    "status": "active",
    "motherTag": "15",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a32",
    "category": "Calf - Heifer",
    "tag": "23 Pink",
    "oldTag": "",
    "name": "Mosley",
    "currentCalf": "",
    "dob": "2026-03-01",
    "notes": "Born to #12 Bad Mama.  Didn't want the calf",
    "status": "active",
    "motherTag": "12",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a33",
    "category": "Calf - Heifer",
    "tag": "24 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-03-20",
    "notes": "Born to #10. Good mama and little calf has white face.",
    "status": "active",
    "motherTag": "10",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a34",
    "category": "Calf - Steer",
    "tag": "25 Blue",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-03-20",
    "notes": "Born to # 7",
    "status": "active",
    "motherTag": "7",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a35",
    "category": "Calf - Steer",
    "tag": "26 Blue",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-03-20",
    "notes": "Born to # 14",
    "status": "active",
    "motherTag": "14",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a36",
    "category": "Calf - Steer",
    "tag": "27 Blue",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-03-20",
    "notes": "Born to # 8",
    "status": "active",
    "motherTag": "8",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a37",
    "category": "Calf - Heifer",
    "tag": "28 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-04-01",
    "notes": "Born to #16",
    "status": "active",
    "motherTag": "16",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a38",
    "category": "Calf - Steer",
    "tag": "29 Blue",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-04-01",
    "notes": "Born to #20",
    "status": "active",
    "motherTag": "20",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a39",
    "category": "Calf - Steer",
    "tag": "30 Blue",
    "oldTag": "",
    "name": "Henry",
    "currentCalf": "",
    "dob": "2026-04-07",
    "notes": "Born to #19 Clementine.  Bad Mama. We are using Head Gate",
    "status": "active",
    "motherTag": "19",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a40",
    "category": "Calf - Heifer",
    "tag": "31 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-04-08",
    "notes": "Born to #9 Good Mama. ",
    "status": "active",
    "motherTag": "9",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a41",
    "category": "Calf - Heifer",
    "tag": "32 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-04-09",
    "notes": "Born to #22. ",
    "status": "active",
    "motherTag": "22",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a42",
    "category": "Calf - Steer",
    "tag": "33 Blue",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-04-22",
    "notes": "Born to #21",
    "status": "active",
    "motherTag": "21",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  },
  {
    "id": "a43",
    "category": "Calf - Heifer",
    "tag": "34 Pink",
    "oldTag": "",
    "name": "",
    "currentCalf": "",
    "dob": "2026-05-03",
    "notes": "Born to #6",
    "status": "active",
    "motherTag": "6",
    "soldDate": "",
    "soldPrice": "",
    "soldTo": "",
    "deathDate": "",
    "deathReason": ""
  }
];
let herd=load();
function load(){try{const x=localStorage.getItem(STORAGE);return x?JSON.parse(x):INITIAL_DATA.map(x=>({...x}));}catch(e){return INITIAL_DATA.map(x=>({...x}));}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(herd));document.getElementById('lastSaved').textContent='Saved '+new Date().toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});renderAll();}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}
function active(){return herd.filter(x=>x.status==='active')}
function label(c){return c.replace('Calf - ','')}
function stats(){let a=active();return {bull:a.filter(x=>x.category==='Bull').length,cow:a.filter(x=>x.category==='Cow').length,heifer:a.filter(x=>x.category==='Calf - Heifer').length,steer:a.filter(x=>x.category==='Calf - Steer').length,total:a.length,sold:herd.filter(x=>x.status==='sold').length,dead:herd.filter(x=>x.status==='deceased').length};}
function renderDashboard(){let s=stats();$('#summaryCards').innerHTML=[['Total Herd',s.total],['Cows',s.cow],['Bulls',s.bull],['Calves',s.heifer+s.steer]].map(x=>`<div class="stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');let recent=[...herd].sort((a,b)=>(b.updatedAt||b.dob||'').localeCompare(a.updatedAt||a.dob||'')).slice(0,6);$('#recentActivity').innerHTML=recent.map(x=>{let status=x.status==='deceased'?`Deceased${x.deathDate?' • '+fmtDate(x.deathDate):''}${x.deathReason?' • '+x.deathReason:''}`:x.status==='sold'?`Sold${x.soldDate?' • '+fmtDate(x.soldDate):''}${x.soldPrice?' • $'+Number(x.soldPrice).toLocaleString():''}`:x.notes||('Added '+fmtDate(x.dob));return `<div class="activity"><div class="activityHead"><b>${esc(x.tag)} ${x.name?'— '+esc(x.name):''}</b><span class="badge ${x.status==='sold'?'sold':x.status==='deceased'?'dead':''}">${x.status==='active'?'Active':x.status==='sold'?'Sold':'Deceased'}</span></div>${esc(status)}</div>`}).join('')||'<div class="empty">No activity yet.</div>';}
function renderCattle(){let q=($('#searchBox')?.value||'').toLowerCase(), f=$('#typeFilter')?.value||'all';let arr=herd.filter(x=>{let okf=f==='all'?x.status==='active':f==='sold'?x.status==='sold':f==='deceased'?x.status==='deceased':x.status==='active'&&x.category===f;let text=[x.tag,x.oldTag,x.name,x.notes,x.currentCalf].join(' ').toLowerCase();return okf&&(!q||text.includes(q));}).sort((a,b)=>(a.tag||'').localeCompare(b.tag||'',undefined,{numeric:true}));$('#cattleList').innerHTML=arr.map(x=>`<div class="animalRow" data-id="${x.id}"><div class="animalMain"><div class="animalTitle">${esc(x.tag)} ${x.name?'— '+esc(x.name):''}</div><div class="animalSub">${esc(x.category)} • DOB ${esc(fmtDate(x.dob))}${x.currentCalf?' • Current calf: '+esc(x.currentCalf):''}</div></div><span class="badge ${x.status==='sold'?'sold':x.status==='deceased'?'dead':''}">${x.status==='active'?'Active':x.status==='sold'?'Sold':'Deceased'}</span></div>`).join('')||'<div class="empty">No cattle found.</div>';$$('#cattleList .animalRow').forEach(e=>e.onclick=()=>showDetail(e.dataset.id));}
function renderHistory(){let cows=active().filter(x=>x.category==='Cow').sort((a,b)=>(a.tag||'').localeCompare(b.tag||'',undefined,{numeric:true}));$('#cowHistory').innerHTML=cows.map(c=>{let calves=herd.filter(x=>x.motherTag===c.tag);return `<div class="historyRow"><h3>Cow #${esc(c.tag)}${c.name?' — '+esc(c.name):''}</h3><div class="animalSub">${calves.length} calf record${calves.length===1?'':'s'} • Current calf: ${esc(c.currentCalf||'None')}</div>${calves.map(k=>`<div class="historyCalf"><b>${esc(k.tag)}</b> — ${esc(label(k.category))} • ${esc(fmtDate(k.dob))} <span class="badge ${k.status==='sold'?'sold':k.status==='deceased'?'dead':''}">${k.status}</span></div>`).join('')||'<div class="historyCalf">No linked calf records yet.</div>'}</div>`}).join('');}
function renderAll(){renderDashboard();renderCattle();renderHistory();}
function fmtDate(s){if(!s)return '—';let d=new Date(s+'T00:00:00');return isNaN(d)?s:d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');}
function closeModal(){$('#modal').classList.add('hidden');}
function animalForm(defaultCat='Cow',mother=''){openModal(defaultCat==='birth'?'Record Birth':'Add Animal',`<form class="form" id="animalForm"><div class="field"><label>Type</label><select id="fCat"><option>Bull</option><option>Cow</option><option>Calf - Heifer</option><option>Calf - Steer</option></select></div><div class="field"><label>Tag Number *</label><input id="fTag" required placeholder="Example: 35 Pink"></div><div class="field"><label>Old Tag (optional)</label><input id="fOld" placeholder="Example: #250 Red"></div><div class="field"><label>Name (optional)</label><input id="fName" placeholder="Example: Clementine"></div><div class="field"><label>Date of Birth</label><input id="fDob" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Mother / Dam (for calves)</label><select id="fMother"><option value="">— None / Not known —</option>${active().filter(x=>x.category==='Cow').map(c=>`<option value="${esc(c.tag)}" ${c.tag===mother?'selected':''}>#${esc(c.tag)}${c.name?' — '+esc(c.name):''}</option>`).join('')}</select></div><div class="field"><label>Notes</label><textarea id="fNotes" placeholder="Birth notes, temperament, color, etc."></textarea></div><div class="formActions"><button type="button" class="secondary" id="cancelForm">Cancel</button><button class="primary" type="submit">Save Animal</button></div></form>`);if(defaultCat==='Calf - Heifer'||defaultCat==='Calf - Steer')$('#fCat').value=defaultCat;$('#cancelForm').onclick=closeModal;$('#animalForm').onsubmit=e=>{e.preventDefault();let x={id:'a'+Date.now(),category:$('#fCat').value,tag:$('#fTag').value.trim(),oldTag:$('#fOld').value.trim(),name:$('#fName').value.trim(),currentCalf:'',dob:$('#fDob').value,notes:$('#fNotes').value.trim(),status:'active',motherTag:$('#fMother').value,soldDate:'',soldPrice:'',soldTo:'',deathDate:'',deathReason:'',updatedAt:new Date().toISOString()};if(!x.tag){alert('Please enter a tag number.');return}if(herd.some(y=>y.status==='active'&&y.tag.toLowerCase()===x.tag.toLowerCase())){alert('That active tag already exists.');return}herd.push(x);if(x.motherTag){let m=herd.find(y=>y.tag===x.motherTag&&y.category==='Cow');if(m)m.currentCalf=x.tag;}save();closeModal();toast('Animal added.');};}
function showDetail(id){let x=herd.find(y=>y.id===id);if(!x)return;let calves=herd.filter(y=>y.motherTag===x.tag);openModal(`${esc(x.tag)} ${x.name?'— '+esc(x.name):''}`,`<div class="detailGrid"><div class="detail"><small>Type</small><b>${esc(x.category)}</b></div><div class="detail"><small>Status</small><b>${x.status==='active'?'Active':x.status==='sold'?'Sold':'Deceased'}</b></div><div class="detail"><small>DOB</small><b>${esc(fmtDate(x.dob))}</b></div><div class="detail"><small>Old Tag</small><b>${esc(x.oldTag||'—')}</b></div>${x.motherTag?`<div class="detail"><small>Mother</small><b>#${esc(x.motherTag)}</b></div>`:''}${x.currentCalf?`<div class="detail"><small>Current Calf</small><b>${esc(x.currentCalf)}</b></div>`:''}${x.status==='deceased'?`<div class="detail"><small>Date of Death</small><b>${esc(fmtDate(x.deathDate))}</b></div><div class="detail"><small>Reason</small><b>${esc(x.deathReason||'—')}</b></div>`:''}${x.status==='sold'?`<div class="detail"><small>Sale Date</small><b>${esc(fmtDate(x.soldDate))}</b></div><div class="detail"><small>Sale Price</small><b>${x.soldPrice?'$'+Number(x.soldPrice).toLocaleString():'—'}</b></div>`:''}</div><div class="note"><b>Notes</b><br>${esc(x.notes||'No notes.')}</div>${x.category==='Cow'?`<div class="note"><b>Calf History (${calves.length})</b>${calves.map(k=>`<div class="historyCalf">${esc(k.tag)} — ${esc(label(k.category))} — ${esc(fmtDate(k.dob))} — ${esc(k.status)}</div>`).join('')||'<div class="historyCalf">No linked calves yet.</div>'}</div>`:''}<div class="formActions detailActions">${x.status==='active'&&x.category.startsWith('Calf')?`<button class="danger" id="sellBtn">Mark Sold</button>`:''}${x.status==='active'&&x.category==='Cow'?`<button class="primary" id="birthBtn">Record Birth</button>`:''}${x.status==='active'?`<button class="danger" id="deathBtn">Record Death</button>`:''}<button class="secondary" id="editBtn">Edit Record</button></div>`);$('#editBtn').onclick=()=>editAnimal(x.id);if($('#sellBtn'))$('#sellBtn').onclick=()=>markSold(x.id);if($('#deathBtn'))$('#deathBtn').onclick=()=>markDead(x.id);if($('#birthBtn'))$('#birthBtn').onclick=()=>{closeModal();animalForm('Calf - Heifer',x.tag)};}
function editAnimal(id){let x=herd.find(y=>y.id===id);let categoryOptions=['Bull','Cow','Calf - Heifer','Calf - Steer'].map(v=>`<option ${x.category===v?'selected':''}>${v}</option>`).join('');openModal('Edit '+x.tag,`<form class="form" id="editForm"><div class="field"><label>Status</label><select id="eStatus"><option value="active" ${x.status==='active'?'selected':''}>Active</option><option value="sold" ${x.status==='sold'?'selected':''}>Sold</option><option value="deceased" ${x.status==='deceased'?'selected':''}>Deceased</option></select></div><div id="eDeathFields" class="conditionalFields ${x.status==='deceased'?'':'is-hidden'}"><div class="field"><label>Date of Death</label><input id="eDeathDate" type="date" value="${esc(x.deathDate||new Date().toISOString().slice(0,10))}"></div><div class="field"><label>Reason / Cause (optional)</label><input id="eDeathReason" value="${esc(x.deathReason)}" placeholder="Example: injury, illness, unknown"></div></div><div id="eSaleFields" class="conditionalFields ${x.status==='sold'?'':'is-hidden'}"><div class="field"><label>Sale Date</label><input id="eSoldDate" type="date" value="${esc(x.soldDate||new Date().toISOString().slice(0,10))}"></div><div class="field"><label>Sale Price (optional)</label><input id="eSoldPrice" type="number" min="0" step="0.01" value="${esc(x.soldPrice)}"></div><div class="field"><label>Buyer (optional)</label><input id="eSoldTo" value="${esc(x.soldTo)}"></div></div><div class="field"><label>Type</label><select id="eCat">${categoryOptions}</select></div><div class="field"><label>Tag</label><input id="eTag" value="${esc(x.tag)}" required></div><div class="field"><label>Name</label><input id="eName" value="${esc(x.name)}"></div><div class="field"><label>Old Tag</label><input id="eOld" value="${esc(x.oldTag)}"></div><div class="field"><label>Date of Birth</label><input id="eDob" type="date" value="${esc(x.dob)}"></div><div class="field"><label>Notes</label><textarea id="eNotes">${esc(x.notes)}</textarea></div><div class="formActions"><button type="button" class="secondary" id="cancelEdit">Cancel</button><button class="primary">Save Changes</button></div></form>`);let toggleStatusFields=()=>{let status=$('#eStatus').value;$('#eDeathFields').classList.toggle('is-hidden',status!=='deceased');$('#eSaleFields').classList.toggle('is-hidden',status!=='sold')};$('#eStatus').onchange=toggleStatusFields;$('#cancelEdit').onclick=closeModal;$('#editForm').onsubmit=e=>{e.preventDefault();let newStatus=$('#eStatus').value;x.category=$('#eCat').value;x.tag=$('#eTag').value.trim();x.name=$('#eName').value.trim();x.oldTag=$('#eOld').value.trim();x.dob=$('#eDob').value;x.notes=$('#eNotes').value.trim();x.status=newStatus;if(newStatus==='deceased'){x.deathDate=$('#eDeathDate').value;x.deathReason=$('#eDeathReason').value.trim();x.soldDate='';x.soldPrice='';x.soldTo=''}else if(newStatus==='sold'){x.soldDate=$('#eSoldDate').value;x.soldPrice=$('#eSoldPrice').value;x.soldTo=$('#eSoldTo').value.trim();x.deathDate='';x.deathReason=''}else{x.soldDate='';x.soldPrice='';x.soldTo='';x.deathDate='';x.deathReason=''}x.updatedAt=new Date().toISOString();save();closeModal();toast(newStatus==='deceased'?'Recorded as deceased.':'Changes saved.');};}
function markSold(id){let x=herd.find(y=>y.id===id);openModal('Mark '+x.tag+' as Sold',`<form class="form" id="saleForm"><div class="field"><label>Sale Date</label><input id="sDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Sale Price (optional)</label><input id="sPrice" type="number" min="0" step="0.01" placeholder="0.00"></div><div class="field"><label>Buyer (optional)</label><input id="sBuyer" placeholder="Buyer name"></div><div class="formActions"><button type="button" class="secondary" id="cancelSale">Cancel</button><button class="primary">Mark Sold</button></div></form>`);$('#cancelSale').onclick=closeModal;$('#saleForm').onsubmit=e=>{e.preventDefault();x.status='sold';x.soldDate=$('#sDate').value;x.soldPrice=$('#sPrice').value;x.soldTo=$('#sBuyer').value.trim();x.updatedAt=new Date().toISOString();save();closeModal();toast('Marked sold. History was kept.');};}
function markDead(id){let x=herd.find(y=>y.id===id);openModal('Record Death — '+x.tag,`<form class="form" id="deathForm"><p class="formHelp">The animal will be removed from the active-herd count, but its complete record and calf history will be kept.</p><div class="field"><label>Date of Death</label><input id="dDate" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>Reason / Cause (optional)</label><input id="dReason" placeholder="Example: injury, illness, unknown"></div><div class="formActions"><button type="button" class="secondary" id="cancelDeath">Cancel</button><button class="danger" type="submit">Confirm Deceased</button></div></form>`);$('#cancelDeath').onclick=closeModal;$('#deathForm').onsubmit=e=>{e.preventDefault();x.status='deceased';x.deathDate=$('#dDate').value;x.deathReason=$('#dReason').value.trim();x.soldDate='';x.soldPrice='';x.soldTo='';x.updatedAt=new Date().toISOString();save();closeModal();toast('Recorded as deceased.');};}
function exportCSV(){let headers=['Status','Category','Tag #','Old Tag','Name','Mother/Dam','Current Calf','Date of Birth','Sold Date','Sale Price','Buyer','Death Date','Death Reason','Notes'];let rows=herd.map(x=>[x.status,x.category,x.tag,x.oldTag,x.name,x.motherTag,x.currentCalf,x.dob,x.soldDate,x.soldPrice,x.soldTo,x.deathDate,x.deathReason,x.notes]);let csv=[headers,...rows].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');download(csv,'rayburn-herd-'+new Date().toISOString().slice(0,10)+'.csv','text/csv');toast('Spreadsheet created.');}
function download(content,name,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function backup(){download(JSON.stringify({app:'Rayburn Herd',version:2,exportedAt:new Date().toISOString(),herd},null,2),'rayburn-herd-backup-'+new Date().toISOString().slice(0,10)+'.json','application/json');toast('Backup file created.');}
function restore(file){let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.herd))throw Error();if(confirm('Restore this backup? This replaces the herd currently on this phone.')){herd=x.herd;save();toast('Backup restored.');}}catch(e){alert('That backup file could not be read.')}};r.readAsText(file);}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function showScreen(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.screen===id));}
$$('.tab').forEach(t=>t.onclick=()=>showScreen(t.dataset.screen));$('#closeModal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#exportBtn').onclick=exportCSV;$('#exportTop').onclick=exportCSV;$('#backupBtn').onclick=backup;$('#restoreFile').onchange=e=>e.target.files[0]&&restore(e.target.files[0]);$('#searchBox').oninput=renderCattle;$('#typeFilter').onchange=renderCattle;
$$('[data-action]').forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==='add-cow')animalForm('Cow');else if(a==='add-bull')animalForm('Bull');else if(a==='birth')animalForm('Calf - Heifer');else if(a==='add-animal')animalForm('Cow');else if(a==='search'){showScreen('cattle');setTimeout(()=>$('#searchBox').focus(),100)}});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));renderAll();document.getElementById('lastSaved').textContent='Herd loaded • '+stats().total+' active cattle';
